name: TomStock Workflow

on:
  schedule:
    - cron:  '0 */5 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Use credentials
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          SP_ID: ${{ secrets.SP_ID_TOMSTOCK }}
        run: |
          echo "$CREDENTIALS_JSON" > keys.json
          echo "$SP_ID" > sp_id.txt

      - name: execute py script
        run: python ./app.py
